import os
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy import Column, Integer, String, Float
from sqlalchemy.ext.declarative import declarative_base
from dotenv import load_dotenv

load_dotenv()

DB_HOST = os.getenv('DB_HOST')
DB_PORT = os.getenv('DB_PORT')
DB_NAME = os.getenv('DB_NAME')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')

db_string = f'postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}'
db = create_engine(db_string)
session = sessionmaker(bind=db)
s = session()

Base = declarative_base()

class KiwoomStock(Base):
    __tablename__ = 'kiwoom_stocks'

    id = Column(Integer, primary_key=True)
    code = Column(String)
    trade_date = Column(String)
    timestamp = Column(String)
    current_price = Column(Integer)
    open_price = Column(Integer)
    high = Column(Integer)
    low = Column(Integer)
    volume = Column(Integer)
    cum_volume = Column(Integer)
    trade_sell_hoga1 = Column(Integer)
    trade_buy_hoga1 = Column(Integer)
    hoga_date = Column(Integer)
    sell_hoga10 = Column(Integer)
    sell_hoga9 = Column(Integer)
    sell_hoga8 = Column(Integer)
    sell_hoga7 = Column(Integer)
    sell_hoga6 = Column(Integer)
    sell_hoga5 = Column(Integer)
    sell_hoga4 = Column(Integer)
    sell_hoga3 = Column(Integer)
    sell_hoga2 = Column(Integer)
    sell_hoga1 = Column(Integer)
    buy_hoga1 = Column(Integer)
    buy_hoga2 = Column(Integer)
    buy_hoga3 = Column(Integer)
    buy_hoga4 = Column(Integer)
    buy_hoga5 = Column(Integer)
    buy_hoga6 = Column(Integer)
    buy_hoga7 = Column(Integer)
    buy_hoga8 = Column(Integer)
    buy_hoga9 = Column(Integer)
    buy_hoga10 = Column(Integer)
    sell_hoga10_stack = Column(Integer)
    sell_hoga9_stack = Column(Integer)
    sell_hoga8_stack = Column(Integer)
    sell_hoga7_stack = Column(Integer)
    sell_hoga6_stack = Column(Integer)
    sell_hoga5_stack = Column(Integer)
    sell_hoga4_stack = Column(Integer)
    sell_hoga3_stack = Column(Integer)
    sell_hoga2_stack = Column(Integer)
    sell_hoga1_stack = Column(Integer)
    buy_hoga1_stack = Column(Integer)
    buy_hoga2_stack = Column(Integer)
    buy_hoga3_stack = Column(Integer)
    buy_hoga4_stack = Column(Integer)
    buy_hoga5_stack = Column(Integer)
    buy_hoga6_stack = Column(Integer)
    buy_hoga7_stack = Column(Integer)
    buy_hoga8_stack = Column(Integer)
    buy_hoga9_stack = Column(Integer)
    buy_hoga10_stack = Column(Integer)
    total_buy_hoga_stack = Column(Integer)
    total_sell_hoga_stack = Column(Integer)
    net_buy_hoga_stack = Column(Integer)
    net_sell_hoga_stack = Column(Integer)
    ratio_buy_hoga_stack = Column(Integer)
    ratio_sell_hoga_stack = Column(Integer)


class KiwoomFutures(Base):
    __tablename__ = 'kiwoom_futures'

    id = Column(Integer, primary_key=True)
    code = Column(String)
    trade_date = Column(String)
    timestamp = Column(String)
    current_price = Column(Float)
    open_price = Column(Float)
    high = Column(Float)
    low = Column(Float)
    volume = Column(Float)
    cum_volume = Column(Float)
    trade_sell_hoga1 = Column(Float)
    trade_buy_hoga1 = Column(Float)
    hoga_date = Column(Integer)
    sell_hoga10 = Column(Float)
    sell_hoga9 = Column(Float)
    sell_hoga8 = Column(Float)
    sell_hoga7 = Column(Float)
    sell_hoga6 = Column(Float)
    sell_hoga5 = Column(Float)
    sell_hoga4 = Column(Float)
    sell_hoga3 = Column(Float)
    sell_hoga2 = Column(Float)
    sell_hoga1 = Column(Float)
    buy_hoga1 = Column(Float)
    buy_hoga2 = Column(Float)
    buy_hoga3 = Column(Float)
    buy_hoga4 = Column(Float)
    buy_hoga5 = Column(Float)
    buy_hoga6 = Column(Float)
    buy_hoga7 = Column(Float)
    buy_hoga8 = Column(Float)
    buy_hoga9 = Column(Float)
    buy_hoga10 = Column(Float)
    sell_hoga10_stack = Column(Float)
    sell_hoga9_stack = Column(Float)
    sell_hoga8_stack = Column(Float)
    sell_hoga7_stack = Column(Float)
    sell_hoga6_stack = Column(Float)
    sell_hoga5_stack = Column(Float)
    sell_hoga4_stack = Column(Float)
    sell_hoga3_stack = Column(Float)
    sell_hoga2_stack = Column(Float)
    sell_hoga1_stack = Column(Float)
    buy_hoga1_stack = Column(Float)
    buy_hoga2_stack = Column(Float)
    buy_hoga3_stack = Column(Float)
    buy_hoga4_stack = Column(Float)
    buy_hoga5_stack = Column(Float)
    buy_hoga6_stack = Column(Float)
    buy_hoga7_stack = Column(Float)
    buy_hoga8_stack = Column(Float)
    buy_hoga9_stack = Column(Float)
    buy_hoga10_stack = Column(Float)
    total_buy_hoga_stack = Column(Float)
    total_sell_hoga_stack = Column(Float)
    net_buy_hoga_stack = Column(Float)
    net_sell_hoga_stack = Column(Float)
    ratio_buy_hoga_stack = Column(Float)
    ratio_sell_hoga_stack = Column(Float)

if __name__ == '__main__':
    KiwoomStock.__table__.create(bind=db, checkfirst=True)
    KiwoomFutures.__table__.create(bind=db, checkfirst=True)

    # s.execute(KiwoomStock.__table__.insert(), {'code': 'aaaa'})
    # s.commit()
    #
    # s.query(KiwoomStock).delete()
    # s.commit()