version: "2"
services:
  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      # testBlockchain will have 1 partition and 1 replicas
      KAFKA_CREATE_TOPICS: "testBlockchain:1:1"
      KAFKA_ZOOKEEPER_CONNECT: host.docker.internal:2181
    volumes:
      - /Users/peepee/desktop/projects/docker/kafka:/var/run/docker.sock
